server:
  port: 8072 # Standard Gateway Port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Auto-create routes based on Service ID (optional but useful)
          lower-case-service-id: true
      routes:
        - id: account-service-route
          # Load Balance (lb) request to the service named 'ekam-account-service'
          uri: lb://ekam-account-service
          predicates:
            - Path=/accounts/** # If user hits localhost:8072/accounts/...
          filters:
            - RewritePath=/accounts/(?<segment>.*), /$\{segment} # Strip '/accounts' prefix before forwarding
